server:
  port: 8012

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8010/eureka
spring:
  application:
    name: user-client
  datasource:
    url: jdbc:mysql://localhost:3306/develop?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  #config-location: classpath:mybatis-config.xml
  type-aliases-package: com.liuaq.common.entity.base

logging:
  level:
    root: info